/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxDma_Dma.h"
#include "IfxDma.h"
#include "IfxPort.h"
#include "IfxSrc.h"

#include "XinDongLib/XinDong_Config.h"
#include "XinDongLib/Intercore.h"
#include "XinDongLib/Time.h"
#include "XinDongLib/IO.h"
#include "XinDongLib/Camera.h"
#include "XinDongLib/Display.h"
#include "XinDongLib/Interrupts.h"

#include "Ifx_Types.h"
#include "IfxSrc.h"
#include "IfxScuEru.h"

void Int_Test(void) {

}



IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;
uint8 g_Image_main[CAM_IMAGE_HEIGHT][CAM_IMAGE_WIDTH];
void core0_main(void) {
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    // initialize timer
//    Time_Start();
    // initialize LEDs and DIP switches, and the input for detecting battery balancing connector

    // if battery balancing connector not connected
    // then set one of the LED and wait until it is connected

    // allow initialization of other cores
    Intercore_AllowInitialize();
    // initialize other modules


    OLED_Init();
    OLED_ShowString(0, 0, "system start", OLED_8X16);
    for (uint8 i = 0; i < 128; i++) {
        OLED_DrawPoint(i, 48);
    }
    OLED_Update();

    IfxPort_setPinMode(IO_LED1_PORT, IO_LED1_PIN, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinState(IO_LED1_PORT, IO_LED1_PIN, IfxPort_State_high);

    IfxPort_setPinMode(IO_LED2_PORT, IO_LED2_PIN, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinState(IO_LED2_PORT, IO_LED2_PIN, IfxPort_State_high);

    IfxPort_setPinMode(IO_LED3_PORT, IO_LED3_PIN, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinState(IO_LED3_PORT, IO_LED3_PIN, IfxPort_State_high);

    IfxPort_setPinMode(IO_LED4_PORT, IO_LED4_PIN, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinState(IO_LED4_PORT, IO_LED4_PIN, IfxPort_State_high);

    for(uint8 pin = 0; pin < 8; pin++) {
        IfxPort_setPinModeInput(&MODULE_P02, pin, IfxPort_InputMode_noPullDevice);
    }

//    typedef struct
//    {
//        IfxDma_Dma                dmaHandle;                         /* Module handle to HW module SFR set              */
//        IfxDma_Dma_Config         dmaConfig;                         /* Module configuration structure                  */
//        IfxDma_Dma_ChannelConfig  dmaChNCfg;                         /* DMA whole channel configurations                */
//        IfxDma_Dma_Channel        dmaChannel;                        /* DMA channel configuration set                   */
//        uint32                    successfulDmaTransaction;          /* Number of successful DMA transactions           */
//        uint32                    failedDmaTransaction;              /* Number of failed DMA transactions               */
//        void                     *pSourceAddressForDmaTransfer;      /* DMA data source address - reload value          */
//        void                     *pDestinationAddressForDmaTransfer; /* DMA data destination address - reload v.        */
//    } dmaParams;
//    #define DMA_CHANNEL_ID      IfxDma_ChannelId_0     /* DMA Channel Id used to transfer data              */
//    #define DATA_ARRAY_LENGTH   10                     /* Data Length of the DMA transaction in words       */
//    dmaParams g_DMA;
//    /* Load default module configuration into configuration structure */
//    IfxDma_Dma_initModuleConfig(&g_DMA.dmaConfig, &MODULE_DMA);
//
//    /* Initialize module with configuration. */
//    IfxDma_Dma_initModule(&g_DMA.dmaHandle, &g_DMA.dmaConfig);
//
//    /* Get/initialize DMA channel configuration for all DMA channels otherwise use &g_Dma.dmaChannel as target */
//    IfxDma_Dma_initChannelConfig(&g_DMA.dmaChNCfg, &g_DMA.dmaHandle);
//
//    /* Set desired DMA channel: Channel 0 is used */
//    g_DMA.dmaChNCfg.channelId = DMA_CHANNEL_ID;
//
//    /* Setup the operation mode/settings for DMA channel */
//    g_DMA.dmaChNCfg.moveSize = IfxDma_ChannelMoveSize_8bit;
//
//    /* Set the number of DMA transfers */
//    g_DMA.dmaChNCfg.transferCount = 1;
//
//    /* Execute the DMA transaction with only one trigger */
//    g_DMA.dmaChNCfg.requestMode = IfxDma_ChannelRequestMode_completeTransactionPerRequest;
//
//    /* Set destination and source address data to DMA channel */
//    uint8 destination;
//    g_DMA.dmaChNCfg.sourceAddress      = (uint32)(&(MODULE_P02.IN.U));
//    g_DMA.dmaChNCfg.destinationAddress = (uint32) &destination;
//
//    /* Setup the specific DMA channel configuration */
//    IfxDma_Dma_initChannel(&g_DMA.dmaChannel, &g_DMA.dmaChNCfg);
//
//    /* Save start address of source and destination buffers, into the Application global variable */
//
//    //g_DMA.pSourceAddressForDmaTransfer      = CAM_D0_PORT;
//    //g_DMA.pDestinationAddressForDmaTransfer = &destination;


    // wait for other cores to finish initialization
    Intercore_CPU0_Ready();

    while (Intercore_ReadyToGo() == 0)
        ;




    IfxPort_setPinState(IO_LED1_PORT, IO_LED1_PIN, IfxPort_State_low);









    while (1) {
        // some code to indicate that the core is not dead
//        IfxDma_Dma_initChannel(&g_DMA.dmaChannel, &g_DMA.dmaChNCfg);
//        IfxDma_Dma_startChannelTransaction(&g_DMA.dmaChannel);
//        while(IfxDma_Dma_getAndClearChannelInterrupt(&g_DMA.dmaChannel) != TRUE)
//        {
//            __nop(); /* NOP == Do nothing - No operation */
//        }

//        if (destination & 0x01) IfxPort_setPinState(IO_LED2_PORT, IO_LED2_PIN, IfxPort_State_high);
//        else IfxPort_setPinState(IO_LED2_PORT, IO_LED2_PIN, IfxPort_State_low);
//        if (destination & 0x02) IfxPort_setPinState(IO_LED3_PORT, IO_LED3_PIN, IfxPort_State_high);
//        else IfxPort_setPinState(IO_LED3_PORT, IO_LED3_PIN, IfxPort_State_low);
//
//        Time_Delay_us(1000000);
//        IfxPort_setPinState(IO_LED1_PORT, IO_LED1_PIN, IfxPort_State_high);
//        Time_Delay_us(1000000);
//        IfxPort_setPinState(IO_LED1_PORT, IO_LED1_PIN, IfxPort_State_low);
        static uint8 state_pclk = 0, state_vsync = 0;
        static uint32 pixel_count = 0, pixel_count_max = 0;

        if(state_pclk == 1 && IfxPort_getPinState(CAM_PCLK_HW_PORT, CAM_PCLK_HW_PIN) == 0) {
            state_pclk = 0;  // 传输完成一个像素，接下来idle

        }else if(state_pclk == 0 && IfxPort_getPinState(CAM_PCLK_HW_PORT, CAM_PCLK_HW_PIN) == 1) {
            state_pclk = 1;  // reading finished
            // 开始读取像素
            if (state_vsync == 1 && IfxPort_getPinState(CAM_VSYNC_HW_PORT, CAM_VSYNC_HW_PIN) == 0) {
                // 这帧已经传输完成，接下来idle
//                IfxPort_togglePin(IO_LED3_PORT, IO_LED3_PIN);
                pixel_count_max = pixel_count;
                if (pixel_count_max > 45120 - 1 && pixel_count_max < 45120 + 1) {
//                    IfxPort_setPinState(IO_LED2_PORT, IO_LED2_PIN, IfxPort_State_high);
                } else {
//                    IfxPort_setPinState(IO_LED2_PORT, IO_LED2_PIN, IfxPort_State_low);
                }
                if (g_Image_main[60][94] > 60) {
//                    IfxPort_setPinState(IO_LED4_PORT, IO_LED4_PIN, IfxPort_State_high);
                } else {
//                    IfxPort_setPinState(IO_LED4_PORT, IO_LED4_PIN, IfxPort_State_low);
                }
                pixel_count = 0;
                state_vsync = 0;    // 这帧已经传输完成，接下来idle
            }
            if (state_vsync == 0 && IfxPort_getPinState(CAM_VSYNC_HW_PORT, CAM_VSYNC_HW_PIN) == 1) {
                // 这帧继续传输
                state_vsync = 1;
            }
            if (IfxPort_getPinState(CAM_VSYNC_HW_PORT, CAM_VSYNC_HW_PIN) == 1) {
                if (IfxPort_getPinState(CAM_HSYNC_HW_PORT, CAM_HSYNC_HW_PIN) == 1) {
                    // 在范围内
                    uint8 first, second, gray, r, g, b;
                    if (pixel_count & 0x01 == 0) {
                        first = (uint8)MODULE_P02.IN.U;
                    } else {
                        second = (uint8)MODULE_P02.IN.U;
                        r = (second) >> 3;
                        g = (((second) & 0x07) << 3) + (((first) & 0xE0) >> 5);
                        b = ((first) & 0x1F);
                        gray = (r * 38 + g * 75 + b * 15) >> 5;
                        g_Image_main[(pixel_count/2) / CAM_IMAGE_WIDTH][(pixel_count/2) % CAM_IMAGE_WIDTH] = gray;
                    }
                    pixel_count++;
                }
            }

        }




    }
}

// list out all ISR for CPU0
