/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "XinDongLib/Interrupts.h"
#include "XinDongLib/Intercore.h"
#include "XinDongLib/Bluetooth.h"
#include "XinDongLib/Display.h"
#include "XinDongLib/Encoder.h"
#include "XinDongLib/IMU.h"
#include "XinDongLib/Movements.h"
#include "XinDongLib/Serial.h"
#include "XinDongLib/Ultrasonic.h"
#include "XinDongLib/Time.h"

#include "XinDongLib/Camera.h"
#include "XinDongLib/CV.h"
#include "Display.h"

#include "XinDongLib/Time.h"

#include "Ifx_Types.h"
#include "IfxSrc.h"
#include "IfxScuEru.h"

extern IfxCpu_syncEvent g_cpuSyncEvent;
extern uint8 g_Image_main[CAM_IMAGE_HEIGHT][CAM_IMAGE_WIDTH];
extern uint16 (*writing_img_ptr)[CAM_IMAGE_WIDTH];

void core2_main(void) {
	IfxCpu_enableInterrupts();

	/* !!WATCHDOG2 IS DISABLED HERE!!
	 * Enable the watchdog and service it periodically if it is required
	 */
	IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

	/* Wait for CPU sync event */
	IfxCpu_emitEvent(&g_cpuSyncEvent);
	IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

	// wait for signal to begin initialization
	while (Intercore_InitAllowed() == 0)
		;
	// initialize any module needed

	// wait for other cores to finish initialization
	Intercore_CPU2_Ready();
	while (Intercore_ReadyToGo() == 0)
		;

	while (1) {
		// some code to indicate that the core is not dead
	    uint16 (*reading_img_ptr)[CAM_IMAGE_WIDTH] = Camera_GetLatest();
	    OLED_Clear();
	    if (reading_img_ptr != 0) {
            for (uint8 i = 0; i < 61; i++) {
                for (uint8 j = 0; j < 128; j++) {
                    uint8 second = (uint8)(reading_img_ptr[2*i][j] >> 8);
                    uint8 first = (uint8)reading_img_ptr[2*i][j];
                    uint8 r = (second) >> 3;
                    uint8 g = (((second) & 0x07) << 3) + (((first) & 0xE0) >> 5);
                    uint8 b = ((first) & 0x1F);
                    uint8 gray = (r * 38 + g * 75 + b * 15) >> 5;
                    if (gray > 100) OLED_DrawPoint(j, i);
    //                if (g_Image_main[2*i][j] > 100) OLED_DrawPoint(j, 63-i);
                }
            }
            if(Camera_Release(reading_img_ptr) != 0) IfxPort_setPinState(IO_LED4_PORT, IO_LED4_PIN, IfxPort_State_high);
            else IfxPort_setPinState(IO_LED4_PORT, IO_LED4_PIN, IfxPort_State_low);
            OLED_Update();
	    }

	}
}

// list out all ISR for CPU2
void Periodic_1s_ISR(void){
	;
}

void Periodic_100ms_ISR(void){
	;
}

void Periodic_10ms_ISR(void){
	;
}

void Periodic_PID_ISR(void){
	;
}

void SWINT_User0_ISR(void){
	;
}

void SWINT_User1_ISR(void){
	;
}

void SWINT_User2_ISR(void){
	;
}

void SWINT_User3_ISR(void){
	;
}
