/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "XinDongLib/Interrupts.h"
#include "XinDongLib/Intercore.h"
#include "XinDongLib/Bluetooth.h"
#include "XinDongLib/Display.h"
#include "XinDongLib/Encoder.h"
#include "XinDongLib/IMU.h"
#include "XinDongLib/Movements.h"
#include "XinDongLib/Serial.h"
#include "XinDongLib/Ultrasonic.h"
#include "XinDongLib/Time.h"

extern IfxCpu_syncEvent g_cpuSyncEvent;

void core2_main(void) {
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG2 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    // wait for signal to begin initialization
    while (Intercore_InitAllowed() == 0)
        ;
    // initialize any module needed
    IfxPort_setPinMode(IO_LED1_PORT, IO_LED1_PIN, IfxPort_Mode_outputPushPullGeneral);
    OLED_Init();
    MPU6050_Init();

    // wait for other cores to finish initialization
    Intercore_CPU2_Ready();
    while (Intercore_ReadyToGo() == 0)
        ;

    Time_Delay_us(100000);
//  OLED_Clear();
//  Time_Delay(1);
//  OLED_Printf(5,5,6,"Hello World!");
//  OLED_ShowChinese(5,30,"加速中");
//  OLED_DrawLine(100,40,90,35);
//  OLED_DrawCircle(90,40,15,1);
//  OLED_DrawTriangle(100,40,90,35,110,45,0);
//  OLED_DrawRectangle(80,40,20,10,0);

    IfxPort_setPinState(IO_LED1_PORT, IO_LED1_PIN, IfxPort_State_low);
    float accel_x, accel_y, accel_z;
    float omega_x, omega_y, omega_z;
    float theta_x, theta_y, theta_z;

    MPU6050_Read_Accel();
    MPU6050_Read_Gyro();
    MPU6050_Read_Theta();

    MPU6050_Set_AccelOffset();
    MPU6050_Set_OmegaOffset();
    MPU6050_Set_ThetaOffset();

    while (1) {
        // some code to indicate that the core is not dead
        OLED_Clear();

        MPU6050_Read_Accel();
        MPU6050_Get_Accel(&accel_x,&accel_y,&accel_z);
        OLED_Printf(5,15,6,"%f",accel_x);
        OLED_Printf(5,25,6,"%f",accel_y);
        OLED_Printf(5,35,6,"%f",accel_z);

        MPU6050_Read_Gyro();
        MPU6050_Get_Omega(&omega_x,&omega_y,&omega_z);
        OLED_Printf(65,15,6,"%f",omega_x);
        OLED_Printf(65,25,6,"%f",omega_y);
        OLED_Printf(65,35,6,"%f",omega_z);

        MPU6050_Read_Theta();
        MPU6050_Get_Theta(&theta_x, &theta_y,&theta_z);
        OLED_Printf(5,45,6,"%06.3f",theta_x);
        OLED_Printf(5,55,6,"%06.3f",theta_y);
        OLED_Printf(65,45,6,"%06.3f",theta_z);
//        OLED_Printf(65,35,6,"%f",mpuData[6]);
        Time_Delay_us(50000);
        OLED_Update();
        IfxPort_togglePin(IO_LED1_PORT, IO_LED1_PIN);
    }
}

// list out all ISR for CPU2
void Periodic_1s_ISR(void){
    ;
}

void Periodic_100ms_ISR(void){
    ;
}

void Periodic_10ms_ISR(void){
    ;
}

void Periodic_PID_ISR(void){
    ;
}

void SWINT_User0_ISR(void){
    ;
}

void SWINT_User1_ISR(void){
    ;
}

void SWINT_User2_ISR(void){
    ;
}

void SWINT_User3_ISR(void){
    ;
}
