/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC37XPD
 * - package : LFBGA292
 */

#include "aurix_pin_mappings.h"


/* GPIO pin configuration */

static const IfxPort_Io_ConfigPin gpio_pin_table[] = 
{
    IFXCFG_P00_0_IO_CONFIG,
    IFXCFG_P00_1_IO_CONFIG,
    IFXCFG_P00_2_IO_CONFIG,
    IFXCFG_P00_3_IO_CONFIG,
    IFXCFG_P00_7_IO_CONFIG,
    IFXCFG_P00_8_IO_CONFIG,
    IFXCFG_P00_9_IO_CONFIG,
    IFXCFG_P02_0_IO_CONFIG,
    IFXCFG_P02_1_IO_CONFIG,
    IFXCFG_P02_2_IO_CONFIG,
    IFXCFG_P02_3_IO_CONFIG,
    IFXCFG_P02_6_IO_CONFIG,
    IFXCFG_P02_7_IO_CONFIG,
    IFXCFG_P02_8_IO_CONFIG,
    IFXCFG_P15_0_IO_CONFIG,
    IFXCFG_P20_7_IO_CONFIG,
    IFXCFG_P20_8_IO_CONFIG,
    IFXCFG_P20_9_IO_CONFIG,
    IFXCFG_P20_10_IO_CONFIG,
    IFXCFG_P20_11_IO_CONFIG,
    IFXCFG_P20_12_IO_CONFIG,
    IFXCFG_P20_13_IO_CONFIG,
    IFXCFG_P20_14_IO_CONFIG,
    IFXCFG_P21_6_IO_CONFIG
};

static const IfxPort_Io_Config gpio_io_config_table = 
{
    sizeof(gpio_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)gpio_pin_table
};

extern void gpio_init_pins(void)
{
    IfxPort_Io_initModule(&gpio_io_config_table);
}


/* ASCLIN2 pin configuration */

static const IfxPort_Io_ConfigPin asclin2_pin_table[] = 
{
    IFXCFG_P33_8_IO_CONFIG,
    IFXCFG_P33_9_IO_CONFIG
};

static const IfxPort_Io_Config asclin2_io_config_table = 
{
    sizeof(asclin2_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)asclin2_pin_table
};

extern void asclin2_init_pins(void)
{
    IfxPort_Io_initModule(&asclin2_io_config_table);
}


/* ASCLIN3 pin configuration */

static const IfxPort_Io_ConfigPin asclin3_pin_table[] = 
{
    IFXCFG_P15_6_IO_CONFIG,
    IFXCFG_P15_7_IO_CONFIG
};

static const IfxPort_Io_Config asclin3_io_config_table = 
{
    sizeof(asclin3_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)asclin3_pin_table
};

extern void asclin3_init_pins(void)
{
    IfxPort_Io_initModule(&asclin3_io_config_table);
}


/* ERUIN0 pin configuration */

static const IfxPort_Io_ConfigPin eruin0_pin_table[] = 
{
    IFXCFG_P15_4_IO_CONFIG
};

static const IfxPort_Io_Config eruin0_io_config_table = 
{
    sizeof(eruin0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)eruin0_pin_table
};

extern void eruin0_init_pins(void)
{
    IfxPort_Io_initModule(&eruin0_io_config_table);
}


/* ERUIN3 pin configuration */

static const IfxPort_Io_ConfigPin eruin3_pin_table[] = 
{
    IFXCFG_P10_3_IO_CONFIG
};

static const IfxPort_Io_Config eruin3_io_config_table = 
{
    sizeof(eruin3_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)eruin3_pin_table
};

extern void eruin3_init_pins(void)
{
    IfxPort_Io_initModule(&eruin3_io_config_table);
}


/* ERUIN5 pin configuration */

static const IfxPort_Io_ConfigPin eruin5_pin_table[] = 
{
    IFXCFG_P15_8_IO_CONFIG
};

static const IfxPort_Io_Config eruin5_io_config_table = 
{
    sizeof(eruin5_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)eruin5_pin_table
};

extern void eruin5_init_pins(void)
{
    IfxPort_Io_initModule(&eruin5_io_config_table);
}


/* ERUIN6 pin configuration */

static const IfxPort_Io_ConfigPin eruin6_pin_table[] = 
{
    IFXCFG_P11_10_IO_CONFIG
};

static const IfxPort_Io_Config eruin6_io_config_table = 
{
    sizeof(eruin6_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)eruin6_pin_table
};

extern void eruin6_init_pins(void)
{
    IfxPort_Io_initModule(&eruin6_io_config_table);
}


/* GPTONE0 pin configuration */

static const IfxPort_Io_ConfigPin gptone0_pin_table[] = 
{
    IFXCFG_P33_6_IO_CONFIG,
    IFXCFG_P33_7_IO_CONFIG
};

static const IfxPort_Io_Config gptone0_io_config_table = 
{
    sizeof(gptone0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)gptone0_pin_table
};

extern void gptone0_init_pins(void)
{
    IfxPort_Io_initModule(&gptone0_io_config_table);
}


/* I2C0 pin configuration */

static const IfxPort_Io_ConfigPin i2c0_pin_table[] = 
{
    IFXCFG_P13_1_IO_CONFIG,
    IFXCFG_P13_2_IO_CONFIG
};

static const IfxPort_Io_Config i2c0_io_config_table = 
{
    sizeof(i2c0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)i2c0_pin_table
};

extern void i2c0_init_pins(void)
{
    IfxPort_Io_initModule(&i2c0_io_config_table);
}


/* TOUT53 pin configuration */

static const IfxPort_Io_ConfigPin tout53_pin_table[] = 
{
    IFXCFG_P21_2_IO_CONFIG
};

static const IfxPort_Io_Config tout53_io_config_table = 
{
    sizeof(tout53_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)tout53_pin_table
};

extern void tout53_init_pins(void)
{
    IfxPort_Io_initModule(&tout53_io_config_table);
}


/* TOUT54 pin configuration */

static const IfxPort_Io_ConfigPin tout54_pin_table[] = 
{
    IFXCFG_P21_3_IO_CONFIG
};

static const IfxPort_Io_Config tout54_io_config_table = 
{
    sizeof(tout54_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)tout54_pin_table
};

extern void tout54_init_pins(void)
{
    IfxPort_Io_initModule(&tout54_io_config_table);
}


/* TOUT94 pin configuration */

static const IfxPort_Io_ConfigPin tout94_pin_table[] = 
{
    IFXCFG_P13_3_IO_CONFIG
};

static const IfxPort_Io_Config tout94_io_config_table = 
{
    sizeof(tout94_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)tout94_pin_table
};

extern void tout94_init_pins(void)
{
    IfxPort_Io_initModule(&tout94_io_config_table);
}

